### PR TITLE
Create week-11.md

### PR DESCRIPTION
**Pull request by pherterich**
Started meeting notes for open source software session - no input needed as long as it is WIP

### CODE REVIEW

**Review by yochannah — COMMENTED** [review]
this looks really great! One suggestion is to ask people to review another person's code, so they get a feel for what it is like reviewing so neutral third-party code can behelpful, where there's no skin in the game. 

No obligation to use this at all, but might be helpful: https://github.com/intermine/internships/blob/master/call-templates/code-review.md

**Comment by pherterich** [comment]
Thanks @yochannah - this looks amazing. Wasn't sure what a good exercise is and if that is too much too ask but I'll include that as it fits what I had in my head but didn't know how to structure/write up!

**Comment by pherterich** [comment]
Incorporated and ready for review :)

**Comment by GemmaTuron** [comment]
Hi,

As I said in the call I'll be happy to contribute a repo to get reviewed and constructively criticised !

**Comment by pherterich** [comment]
Finally got back to this and adjusted the notes following the feedback from the session. @yochannah would you mind approving and we can merge this in 🙏🏻 ?

**Review by yochannah — APPROVED** [review]

**Comment by yochannah** [comment]
thanks Patricia!

**Pull request merged**
